pipeline
{
  agent { label 'Dev' }

  tools { maven Maven }

  stages{

    stage('Build')
    {
      steps
      {
        echo "This is building"
        sh '''
        mvn validate
        mvn compile
        mvn package
        '''
      }

      post
      {
        success{
         echo "Build stage success" 
         archiveArtifacts artifacts: '**/target/*war' 
        }
        failure { echo "Build failed" }
      }

    }
    
  }
}