pipeline
{
  agent any

  stages{

    stage('Build')
    {
      steps
      {
        echo "This is building"
      }
    }
    stage('Test')
    {
      steps
      {
        echo "This is testing"
      }
    }
    stage('Deploy')
    {
      steps
      {
        echo "This is deploying"
      }
    }        
  }
}